name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          # Pandoc is only needed if you have RST/PDF exports later
          # sudo apt-get install -y pandoc

      - name: Prepare documentation
        run: |
          # Use root README.md as the main page
          cp README.md docs/source/index.md
          # Remove all img.shields.io badges
          sed -i '/https:\/\/img.shields.io\//d' docs/source/index.md
          # Delete the excess in the beginning
          sed -i '/\*\*📖 For comfortable reading:\*\*/,/^<a id="contents"><\/a>$/ {/^<a id="contents"><\/a>$/!d}' docs/source/index.md

      - name: Build Sphinx docs
        run: |
          cd docs
          make html

      - name: Add .nojekyll
        run: |
          touch ./docs/build/html/.nojekyll 

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          keep_files: true
          force_orphan: true
          