name: Check Markdown links
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    
    
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: './mlc_config.json'